version: '3'
services:
  servidor1:
    container_name: Servidor1
    build:
      context: ./servidor1
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MYSQL_HOST=maestro1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_informacion
      - MYSQL_PORT=3306
    depends_on:
      - maestro1

  servidor2:
    container_name: Servidor2
    build:
      context: ./servidor2
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - MYSQL_HOST=maestro2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=db_informacion
      - MYSQL_PORT=3306
    depends_on:
      - maestro2

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOSTS: "maestro1,maestro2"
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - maestro1
      - maestro2

  maestro1:
    image: mysql:8.0
    container_name: maestro1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=db_informacion
    ports:
      - 3308:3306
    volumes:
      - maestro1_data:/var/lib/mysql

  maestro2:
    image: mysql:8.0
    container_name: maestro2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_informacion
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=db_informacion
    ports:
      - 3309:3306
    volumes:
      - maestro2_data:/var/lib/mysql

volumes:
  maestro1_data:
  maestro2_data:

